---
title: "研究"
---

## 学術論文(査読あり)


-  [1] Omizu, T. and Kunisato. Y.(2024). Exploring Effective Intervention Strategies for Depression as a Complex System: Targeted Interventions through Network Simulations. Japanese Psychological Research. 67,(2),147-161.




## 紀要論文


- [1] 国里愛彦・藁科佳奈・隅田昌孝・村口ゆら・大水拓海 (2023). 横断データに対する心理ネットワーク分析のチュートリアル. 専修人間科学論集 心理学篇 13, (1), pp. 51-67. (https://senshu-u.repo.nii.ac.jp/records/13467)

- [2] 大水拓海・国里愛彦(2025).単一事例研究への心理ネットワーク分析の適用―graphicalVARを用いたチュートリアル―. 専修人間科学論集 心理学篇 15, (1), pp.45-56.


## 学会発表

- [1] Omizu, T., & Kunisato, Y. (2023, July). Network simulation of depression as a complex system with treatment components.In Artificial Life Conference Proceedings 35 (Vol. 2023, No. 1, p. 97). One Rogers Street, Cambridge, MA 02142-1209,USA journals-info@ mit. edu: MIT Press.  (https://direct.mit.edu/isal/proceedings/isal/35/97/116843) (審査あり)

- [2] 大水拓海(2023) 日本心理学会第87回 若手の会企画「学部生・高校生プレゼンバトル」「複雑系としてのうつ病の数理シミュレーション」2023年9月15-17日 (https://sites.google.com/view/jpaecp-lt/2023)

- [3] 大水拓海・国里愛彦 (2024).  介入標的によってうつ症状低減効果は変わるか？ーネットワークモデルを用いた数理シミュレーションー. 日本心理学会第88回大会.(2024.9.6 - 2024.9.8). ポスター発表.(https://pub.confit.atlas.jp/ja/event/jpa2024/presentation/1D-41).

- [4] 大水拓海・国里愛彦(2024). 症状ネットワークのコネクティビティは症状改善の指標となるか？日本神経回路学会. JNN2024(2024.9.11-9.13). ポスター発表. (https://conf.jnns.org/).

- [5] 大水拓海・国里愛彦(2025).心理ネットワークによる感情粒度の個人差の定量化:オープンデータの二次解析による検証.日本心理学会第89回大会. ポスター発表. 2025年9月6日(土) 9:00 〜 10:40

## その他の研究関連のイベント(研究会など)での発表

- [1] Computational Psychiatry and Neurobiology 2024 at University of Tokyo
Yamanaka-Ryo Naito Seminer House by abreuvoir.*Computational Study of Psychotherapy Mechanisms through Psychological Networks and Mathematical Simulations.(oral presentation)* November 4, 2024.


- [2] 大水拓海・国里愛彦(2025). 個別ネットワークの推定精度と解釈可能性.計算論的精神医学コロキウム2025(CPSYTOKYO2025).ポスター発表.2025.2.19-20. 

- [3] 大水拓海(2025).[心理ネットワークを用いたシミュレーション研究](slide/summerschool2025.html).計算論的臨床心理学サマースクール2025. 8月7日.専修大学神田キャンパス.


## 受賞等

- [1] 2020.11.12 専修大学新入生学術奨学生

- [2] 2022.7.5 専修大学学術奨学生

- [3] 大水拓海(2023) 日本心理学会第87回 若手の会企画「学部生・高校生プレゼンバトル」ベストプレゼンター(第1席). 「複雑系としてのうつ病の数理シミュレーション」2023年9月15-17日 (https://sites.google.com/view/jpaecp-lt/2023)

- [4] 2024.3.22 専修大学川島記念賞(学術)

- [5] 2024.3.22 令和5年度専修大学心理学科優秀卒業論文「複雑系としてのうつ病の症状維持と治療作用メカニズムーネットワークモデルを用いた数理シミュレーションによる検討ー」

- [6] 2024 専修大学大学院学術奨学生

- [7] 2025 専修大学大学院学術奨学生

