---
title: "研究"
---

## 学術論文（査読あり）

::: {.pub-list}

**[2]** 江川伊織・**大水拓海**・国里愛彦（印刷中）. 計算論的アプローチにおける不確実性下の意思決定・学習課題：スコーピングレビューによる選定指針. *認知科学*, 33(3), 1-15. [[DOI]]()

**[1]** **Omizu, T.** and Kunisato, Y. (2025). Exploring Effective Intervention Strategies for Depression as a Complex System: Targeted Interventions through Network Simulations. *Japanese Psychological Research*, 67(2), 147–161. [[DOI]](https://doi.org/10.1111/jpr.12553)

:::

---

## 紀要論文

::: {.pub-list}

**[2]** **大水拓海**・国里愛彦（2025）. 単一事例研究への心理ネットワーク分析の適用―graphicalVARを用いたチュートリアル―. *専修人間科学論集 心理学篇*, 15(1), 45–56. [[link]](https://senshu-u.repo.nii.ac.jp/records/2001214)

**[1]** 国里愛彦・藁科佳奈・隅田昌孝・村口ゆら・**大水拓海**（2023）. 横断データに対する心理ネットワーク分析のチュートリアル. *専修人間科学論集 心理学篇*, 13(1), 51–67. [[link]](https://senshu-u.repo.nii.ac.jp/records/13467)

:::

---

## 学会発表

**プログラム公開済みで発表予定のものは，現在[6]-[11]です。発表後に詳細を追記します。**

::: {.pub-list}

**[11]**国里愛彦・**大水拓海**(2026). チュートリアルワークショップ「Pythonによる能動的推論入門」　日本心理学会第90回大会　東京　9月6日(日) 13：40～15：20

**[10]**  加藤めぐみ・**大水拓海**・国里愛彦(2026). 抑うつ症状ネットワークの安定性ランドスケープ分析:オープンデータの二次解析によるシミュレーション.日本心理学会第90回大会　東京　9月6日(日) 9：20～11：00. ポスター発表.

**[9]** **大水拓海**(2026). 大会企画シンポジウム「公認心理師試験から見た公認心理師」話題提供「タイトル未定」.日本心理学会第90回大会　東京　9月4日(金) 13：40～15：20 

**[8]** **大水拓海**(2026).
公募シンポジウム「心理ネットワークアプローチの最前線:研究手法と領域の広がり，心の個別性・複雑性理解への道筋」話題提供「タイトル未定」. 日本心理学会第90回大会　東京　9月4日(金) 9:00~10:40

**[7]** Kato, M., **Omizu, T.,** & Kunisato, Y.(2026, July). Intervention Simulations for Insomnia Using Bridge Centrality in Networks. International Meeting of the Psychometric Society 2026. Yonsei University, Korea. Poster presentation. 

**[6]** **Omizu, T.** & Kunisato, Y.(2026, July). Estimating Inverse Temperature in Individual Networks Using Dynamic Ising Models. International Meeting of the Psychometric Society 2026. Yonsei University, Korea. Poster presentation. 

**[5]** **大水拓海**・国里愛彦（2025）. 心理ネットワークによる感情粒度の個人差の定量化：オープンデータの二次解析による検証. 日本心理学会第89回大会. ポスター発表. 2025年9月6日(土) 9:00 〜 10:40. [[DOI]](https://doi.org/10.4992/pacjpa.89.0_926)

**[4]** **大水拓海**・国里愛彦（2024）. 症状ネットワークのコネクティビティは症状改善の指標となるか？ 日本神経回路学会 JNN2024（2024.9.11-9.13）. ポスター発表. [[link]](https://conf.jnns.org/)

**[3]** **大水拓海**・国里愛彦（2024）. 介入標的によってうつ症状低減効果は変わるか？―ネットワークモデルを用いた数理シミュレーション―. 日本心理学会第88回大会.（2024.9.6 - 2024.9.8）. ポスター発表. [[link]](https://pub.confit.atlas.jp/ja/event/jpa2024/presentation/1D-41)

**[2]** **大水拓海**（2023）. 複雑系としてのうつ病の数理シミュレーション. 日本心理学会第87回 若手の会企画「学部生・高校生プレゼンバトル」. 2023年9月15–17日. [[link]](https://sites.google.com/view/jpaecp-lt/2023)

**[1]** **Omizu, T.** & Kunisato, Y. (2023, July). Network simulation of depression as a complex system with treatment components. In *Artificial Life Conference Proceedings 35* (Vol. 2023, No. 1, p. 97). MIT Press. [[link]](https://direct.mit.edu/isal/proceedings/isal/35/97/116843) （審査あり）

:::

---

## その他の研究関連イベントでの発表

::: {.pub-list}

**[5]** 江川伊織・**大水拓海**・国里愛彦（2026）. 計算論的アプローチにおける不確実性下の意思決定・学習課題：スコーピングレビューによる分類枠組みと選定指針の提案. 計算論的精神医学コロキウム2026（CPSYTOKYO2026）. ポスター発表. 2026年2月19–20日.

**[4]** **大水拓海**・国里愛彦（2026）. 感情粒度の計算論モデル作成の試み：能動的推論によるシミュレーション. 計算論的精神医学コロキウム2026（CPSYTOKYO2026）. ポスター発表. 2026年2月19–20日.

**[3]** **大水拓海**（2025）. [心理ネットワークを用いたシミュレーション研究](slide/summerschool2025.html). 計算論的臨床心理学サマースクール2025. 2025年8月7日. 専修大学神田キャンパス.

**[2]** **大水拓海**・国里愛彦（2025）. 個別ネットワークの推定精度と解釈可能性. 計算論的精神医学コロキウム2025（CPSYTOKYO2025）. ポスター発表. 2025年2月19–20日.

**[1]** **Omizu, T.** & Kunisato, Y. (2024). Computational Study of Psychotherapy Mechanisms through Psychological Networks and Mathematical Simulations. *Computational Psychiatry and Neurobiology 2024 at University of Tokyo*, Yamanaka-Ryo Naito Seminer House by abreuvoir. Oral presentation. November 4, 2024.

:::

---

## 受賞等

::: {.pub-list}

**[9]** 2026年2月26日 日本心理学会第89回大会 **学術大会優秀発表賞**（大水拓海・国里愛彦（2025）. 心理ネットワークによる感情粒度の個人差の定量化：オープンデータの二次解析による検証. 日本心理学会第89回大会. ポスター発表. 2025年9月6日(土) 9:00 〜 10:40）

**[8]** 2026年2月4日 令和7年度専修大学大学院文学研究科**修士論文ポスター優秀発表賞**「心理ネットワークを用いた感情粒度の定量化と感情ラベリングの効果の検証」

**[7]** 2025年 専修大学大学院学術奨学生

**[6]** 2024年 専修大学大学院学術奨学生

**[5]** 2024年3月22日 令和5年度専修大学心理学科**優秀卒業論文**「複雑系としてのうつ病の症状維持と治療作用メカニズム―ネットワークモデルを用いた数理シミュレーションによる検討―」

**[4]** 2024年3月22日 専修大学川島記念賞（学術）

**[3]** 2023年9月 日本心理学会第87回 若手の会企画「学部生・高校生プレゼンバトル」**ベストプレゼンター（第1席）**. [[link]](https://sites.google.com/view/jpaecp-lt/2023)

**[2]** 2022年7月5日 専修大学学術奨学生

**[1]** 2020年11月12日 専修大学新入生学術奨学生

:::
