---
title: "N=1のイジングモデル"
format: html
editor: source
---

## イジングモデルとノードワイズロジスティック回帰が数学的に等価である証明

### データ(値)が取り得る状態を0もしくは2とする場合


説明では，ノードの集合は1~pまで，注目するノードはi，総和用のインデックスとしてjとk(1からpまで動く)，



- 確率変数$\boldsymbol{Y} = (Y_1,Y_2, ...,Y_p)$

- 値；各変数$Y_i \in [0,1]$

- $\theta_k$: ノードkの閾値(バイアス)

- $W_{jk}$: ノードjとkの相互作用(エッジの重み)。$W_{jk} = W_{kj}, W_{kk} = 0$



### 同時確率分布(ボルツマン分布)

変数が0もしくは1の状態をとる場合の同時確率は以下のように定義される

$$P(\boldsymbol{Y} = y) = \frac{1}{Z} exp(\sum_k \theta_k y_k + \sum_{j<k} W_{jk}y_j y_k)$$

### 指数部分(エネルギー関数)の分解

指数部分を$E(y)$と置く

$$E(y) = \sum_k^p \theta_k y_k + \sum_{j<k} W_{jk}y_j y_k$$

注目する変数である$y_i$に関係する項と，関係しない項($X$)に分解する。まず，第1項(閾値の項)を分解する。総和$\sum_{k=1}^p$の中から，$k = i$の場合だけを抜き出す。


$$\sum_{k=1}^p \theta_k y_k = \theta_i y_i + \sum_{k \not{=} i} \theta_k y_k$$

次に，第2項(相互作用項)を分解する。総和$\sum_{j<k}$はすべてのペアの和なので，このペアの中にはiが混ざっているものと混ざっていないものがある。iが関わるペアは$「j = i(かつi<k)」$または$「k = i(かつj<i)」$のいずれかになる。

$$\sum_{j<k} W_{jk} y_j y_k = \sum_{k>i} W_{ik} y_i y_k + \sum_{j<i}W_{ji} y_j y_i + \sum_{j<k,j \not{=}i, k \not{=}i}W_{jk y_j y_k}$$

この式で，右辺第1項と第2項は$y_i$を含むペア，第3項は$y_i$を含まないペアになっている。ここで，$y_i$を含むペアの部分を整理する。$W$は対称行列なので，インデックスを統一してまとめると，「iとつながっているすべての相手j($j \not{=} i$)」との和として書くことができる。

$$(y_iを含む相互作用) = y_i(\sum_{j \not{= i}}W_{ij}y_j)$$

ここまで行ってきた$y_i$に関する分解を統合する。

$$E(y) = (\theta_i y_i +\sum_{j \not = i} W_{ij} y_i y_j) + (\sum_{k \not = i} \theta_k y_k + \sum_ {j<k(j,k \not = i)}W_{jk}_yj y_k)$$
ここで$y_i$を含まない項である第2項をまとめて$Rest(y_{-i})$とおくと，$E(y)$は以下のように「$y_i$にかかる係数部分」と「$y_i$と無関係な部分」が分離できる。

$$ E (y)= y_i (\theta_i + \sum_{j \not = i} W_{ij} y_j) + Rest(y_{-i})$$


分離できたら，$y_i = 1$となる条件付確率を計算する。簡略化のため，線形和を$L_i = \theta_i + \sum_{j \not = i}W_{ij} y_j$と置くと，エネルギーの式は$E(y) = y_i L_i + Rest$と置くことができる。

$$P(y_i = 1 | y_{-i}) = \frac{exp(E(y_i = 1))}{exp(E(y_i = 1) +exp(E(y_i = 0))}$$
ここで$y_i$は0か1のどちらかの状態をとるので，

- $y_i = 1$の時

$$E(y_i = 1) = 1・L_i+Rest = L_i + Rest$$

- $y_i = 0$の時

$$E(y_i = 0) = 0・Li + Rest = Rest$$
となる。

これを確率の式に代入すると，

$$P(y_i = 1 | y_{-i}) = \frac{exp(L_i + Rest)}{exp(L_i + Rest) + exp(Rest)}$$

分母と分子を$exp(Rest)$で割って約分する。

$$P(y_i = 1 | y_{-i}) = \frac{exp(L_i)}{exp(L_i) + 1}$$
分母と分子に$exp(-L_i)$を掛ける。

$$P(y_i = 1 | y_{-i}) = \frac{1}{1+exp(-L_i)}$$

$L_i$をもとの形に戻すと，

$$P(y_i = 1 | y_{-i}) = \frac{1}{1+exp(-(\theta_i + \sum_{j\not = i}W_{ij}y_j))}$$

ロジスティック回帰の式は以下の通りなので，比較すると完全一致することがわかる。

$$P(\boldsymbol{Y} = 1) = \frac{1}{1+exp(-(\beta_0 + \sum_{j\not = i}\beta_{j}y_j))}$$

## 補足1:推定された値の取り出し方と解釈

- ロジスティック回帰の切片と係数はイジングモデルの閾値と結合強度の$\frac{1}{2}$と等しい

- ただしデータが1か-1の状態をとる場合に$\frac{1}{2}$の操作が必要で，データが1か0の状態をとる場合はこの操作は必要ない

- エッジに自己回帰効果は反映されておらず，推定に用いた期間の変数間の無方向の条件付き関連が表現されている

## 補足2:対称化操作

- IsingFitパッケージの内部でも対称化の操作を行っている。その際，ANDルールとORルールのどちらかが用いられる。

- 双方向からの予測で両方とも係数が0ではない場合のみエッジを残し，値を平均するという操作。偽陽性を減らすことができる。

- 推定された$\beta_{ij}$と$\beta_{ji}$のずれは，graphicalVARのように因果の方向性を表すものではなく，推定のノイズであるとみなすため，平均してノイズを消す対称化が行われる。

- 実装は，glmnetパッケージで正則化推定を行って，得られた係数行列bata_matとその転置であるt(beta_mat)を使ってANDルールを使い，両方とも0じゃない数値を足して2(もしくは4)で割った値が最終的な無向グラフになる

- 4で割るのは，ロジスティック回帰の値からイジングに変換するのに2で割り，対称化するときにさらに2で割るため。データが0か1の状態をとるときには対称化のために2で割るだけ。